repos:
  - repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: poetry export --format=requirements.txt --without-hashes --with dev --output=requirements.txt
        pass_filenames: false
        language: system
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: poetry run isort
        types: [python]

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: poetry run black
        types: [python]

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: poetry run flake8
        types: [python]
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package.lock.json

      #- id: mypy
      #  name: mypy
      #  stages: [commit]
      #  language: system
      #  entry: poetry run mypy
      #  args: [ --ignore-missing-imports]
      #  types: [python]
      #  pass_filenames: True
      #  exclude: docs/

      # - id: pytest
      #   name: pytest
      #   stages: [commit]
      #   language: system
      #   entry: poetry run pytest
      #   types: [python]
      #   pass_filenames: false
 
      # - id: pytest-cov
      #   name: pytest
      #   stages: [push]
      #   language: system
      #   entry: poetry run pytest --cov --cov-fail-under=90
      #   types: [python]
      #   pass_filenames: false
