"""filtername

Revision ID: e218632eebc6
Revises: 06d2e5c9987f
Create Date: 2024-03-14 02:59:01.067205+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e218632eebc6"
down_revision: Union[str, None] = "06d2e5c9987f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("filter_model", sa.Column("name", sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("filter_model", "name")
    # ### end Alembic commands ###
