"""serials to cameras, telescopes


Revision ID: 06d2e5c9987f
Revises: e27352687ae5
Create Date: 2024-03-14 01:57:16.721039+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "06d2e5c9987f"
down_revision: Union[str, None] = "e27352687ae5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("camera", sa.Column("serial", sa.String(length=12), nullable=True))
    op.add_column("telescope", sa.Column("serial", sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("telescope", "serial")
    op.drop_column("camera", "serial")
    # ### end Alembic commands ###
